-- ─────────────────────────────────────────────────────────────
-- 창구 둘의 comment 정정 — 「재생성이 되살리지 않는다」→「창구를 다시 불러 되살린다」 (Asung-IMS · 2026-09-20)
--   ⚠️⚠️ comment on function 둘만. 함수 본문·시그니처·security·소유자 무접촉 — 검증 ② 가 md5(prosrc) 로 대조한다.
--   원문 comment 는 20260919192236:149(inv_layer_post_receipt) · 20260919200414:182(inv_layer_post_charge) 에서 그대로 복사하고 그 한 문장만 바꿨다.
--   왜: inv_layer_apply 에 IMS 판이 들어갔다(20260920142635 · bb519c7). 두 comment 의 「⚠️ inv_layer_apply() … 되살리지 않는다(§13-f)」는 이제 거짓이고,
--       원래도 틀린 서술이었다(실물은 0 원 unknown 레이어로 덮어썼고 창구 멱등을 막았다 — ledger-design 4부 「✅ 해소 — inv_layer_apply() 에 IMS 판」).
--   적용된 마이그레이션의 본문 주석(192236:28 · 200414:27)은 못 고친다 — 그 줄은 「그때 그렇게 믿었다」의 기록으로 남는다.
-- 배포: Caleb · supabase db push --db-url "$(cat ~/.asung-testdb-url)"   (⚠️ 테스트 DB Asung-IMS)
-- ─────────────────────────────────────────────────────────────

comment on function public.inv_layer_post_receipt(uuid) is '⭐⭐ 원가의 창구(원가 이식 1차 · 2026-09-19) — 확정된 입고의 원장 행(source ims · po_in · 이 RCV)을 (line_ref, sku, warehouse) 로 접어 inv_layer 한 행/라인을 만든다(bin 은 버린다 · 원장 행 수 ≠ 레이어 행 수는 설계). 수량 = 원장 합(기준까지만 — 두 번 계산하지 않는다) · unit_cost = po_line.unit_price × po.exchange_rate(⚠️ CAD per USD · 곱한다 · 기준통화면 ×1) · cost_source po_line · origin purchase · doc_number RCV · line_ref po_line_id(레이어 키 = 원장 키). 멱등: 같은 4키 레이어가 있으면 건너뛴다 — 백필은 다시 부르기만. 거부(문장): 확정 아님 · base_currency 없음 · 기준통화 아닌데 환율 null·0(어디서 고치는지 말한다) · 원장이 가리키는 po_line 없음. 경고: 기준통화에 환율 적힘(무시) · 원장 행 없음. ⭐ 재고 원가는 인식 시점(발주) 환율 — 결제 환율 차액은 환차손익(Caleb · 회계사 확인 대기 · cost_add 로 바꿀 길은 열림). ⭐ [2026-09-20] inv_layer_apply() 전량 재생성은 이 레이어를 지운 뒤 **이 창구를 다시 불러 되살린다**(20260920142635 · 루프 안 · 입고 단위 doc_task_id) — 환율이 없으면 멈추지 않고 건너뛰어 반환 ims.receipts_skipped · skip_reasons 에 센다(0 이 아니면 그 입고의 원가가 빠진 채다). 옛 문구 「되살리지 않는다」는 틀렸었다 — 실물은 0 원 unknown 레이어로 덮어썼다(ledger-design 4부 「✅ 해소 — inv_layer_apply() 에 IMS 판」). security invoker · append-only';

comment on function public.inv_layer_post_charge(uuid) is '⭐⭐ 원가의 창구 둘째(원가 이식 2차 · 2026-09-19) — 확정된 비용 문서(po_charge)의 배분 줄(po_charge_alloc · 발주 단위 · 박아 둔 금액)을 그 발주의 IMS 입고 레이어(inv_layer.line_ref = po_line.id · cost_source po_line)에 unit_cost×qty 비율로 나눠 inv_layer_cost_add(kind landed)에 얹는다. kind 넷(freight·duty·brokerage·other) 전부 landed(Caleb) — 비용 종류는 doc_number(비용 번호)로 po_charge.kind 를 거슬러 센다. amount CAD(⚠️ CAD per USD · 곱한다 · 기준통화면 ×1) · occurred_on charge_date · line_ref alloc.id · ref_number 발주 번호 · 6자리 · 끝수는 마지막 레이어. 버림(정본 D): 기준 0 → no_basis · 레이어 없음 → no_layers — 금액을 반환에 남긴다(Cin7 대조의 설명된 차이). 멱등: 배분 줄 단위(already_posted). 거부(문장): 권한(purchasing) · 확정 아님 · 환율 없음 · 배분 줄 없음. ⭐ [2026-09-20] inv_layer_apply() 재생성이 cost_add 를 지운 뒤 **이 창구를 다시 불러 되살린다**(20260920142635 · 끝 · 레이어가 가리키는 발주의 확정 비용 · charge_date <= p_until) — 거부되면 건너뛰어 ims.charges_skipped 에, 레이어 없는 발주에만 배분된 비용은 ims.charges_unvisited · 금액에 센다. 옛 문구 「되살리지 않는다」는 틀렸었다(ledger-design 4부 「✅ 해소 — inv_layer_apply() 에 IMS 판」). security invoker · append-only';
