-- 픽·팩 라인 저장을 묶음 upsert(on_conflict=id) 로 바꾸기 위한 전제.
--
-- ⚠️ 왜 바꾸나 (되돌리면 완료가 전면 중단된다):
--   PostgREST upsert 는 명시 id 를 INSERT 컬럼 목록에 싣는데, id 가
--   GENERATED ALWAYS AS IDENTITY 면 rewrite 단계에서 428C9
--   ("cannot insert a non-DEFAULT value into column id") 로 거부된다
--   — 2026-08-06 원격 실측(두 테이블 모두, 실패 보장 REST 프로브).
--   BY DEFAULT 는 자동 생성 동작을 그대로 두고 명시 지정만 추가로 허용한다.
--
-- 안전성: 기존 데이터·시퀀스 무변. 라인 insert 지점은 manager.html 의
-- 분할 생성(id 미지정)뿐이라 시퀀스 충돌 실위험 없음.
-- 배포 순서: 이 SQL 먼저(사람이 db push) → 프론트 나중 — 역순이면
-- 모든 픽·팩 완료가 428C9 로 죽는다.

alter table public.wms_pick_task_lines alter column id set generated by default;
alter table public.wms_pack_task_lines alter column id set generated by default;
